### ISSUE TITLE
pulls too many changes

### ISSUE THREAD

**Issue by dfrieling** [plista/chimney#4]
just tried to run chimney on plista tracking (my HEAD in plista-tracking is 8f421312725), but it pulls in too many changes (those which are in the previous releases already):

```
danielfrieling@DANIELFRIELING:~/plista/dataeng/tracking (next=) ⚡ chimney make debian --package='plista-tracking'                      
====================
Generated changelog:
====================
plista-tracking (2.3.2) stable; urgency=medium

  * fix some unit tests
  * plista-tracking (2.3.5)
  * ..
  * ..
  * ..
  * plista-tracking (2.3.4)
  * Update dependencies
  * plista-tracking (2.3.3)
  * Update dependencies
  * plista-tracking (2.3.2)
  * ...
  * ...

 -- Daniel Frieling <df@plista.com>  Tue, 05 Jul 2016 15:34:24 +0200
```

**Comment by vintage-dreamer** [comment]
The reason is that `git describe --abbrev=0` in this repo probably returns not the latest tag. I guess, it's because you're running the tool while the repository is set on "next", whereas the tags are in "master".
But I've found a way to solve this problem.

**Comment by vintage-dreamer** [comment]
Fixed in the upcoming release.
